from datetime import date, datetime, timezone

from app.schemas.domain import (
    AgentRunRead,
    AgentSourceRead,
    AlertRead,
    ApprovalRead,
    ConnectorRunRead,
    DashboardDepartmentRead,
    DashboardSummaryRead,
    DocumentRead,
    DocumentSearchResponse,
    DocumentSearchResultRead,
    InventoryLedgerRead,
    InventorySyncRead,
    InventoryTransactionRead,
    KpiMetricRead,
    KpiTrendPointRead,
    MeetingDirectiveRead,
    ProductionApprovalLogRead,
    ProductionProcessDetailRead,
    ProductionProcessEventRead,
    ProductionProcessRead,
    ProductionInquiryRead,
    ProductionItemRead,
    QualityNCRRead,
    ReportRead,
    RoleRead,
    SavedQueryRead,
    UserRead,
)

NOW = datetime(2026, 3, 5, 9, 0, tzinfo=timezone.utc)

ROLES = [
    RoleRead(code="platform_admin", name="Platform Admin"),
    RoleRead(code="buyer", name="Buyer"),
    RoleRead(code="quality_manager", name="Quality Manager"),
]

USERS = [
    UserRead(
        id="user-001",
        email="leader@4dvision.co.kr",
        name="심현보",
        department_code="EXEC",
        role_code="platform_admin",
        last_login_at=NOW,
    ),
    UserRead(
        id="user-002",
        email="buyer@4dvision.co.kr",
        name="김구매",
        department_code="PROC",
        role_code="buyer",
        last_login_at=NOW,
    ),
]

SUMMARY = DashboardSummaryRead(
    alerts_today=7,
    weekly_reports=12,
    pending_approvals=5,
    recent_queries=41,
    departments=[
        DashboardDepartmentRead(code="EXEC", name="경영지원", kpi_status="watch"),
        DashboardDepartmentRead(code="PROC", name="구매/자재", kpi_status="risk"),
        DashboardDepartmentRead(code="MES", name="생산/MES", kpi_status="watch"),
        DashboardDepartmentRead(code="QUAL", name="품질", kpi_status="risk"),
    ],
)

ALERTS = [
    AlertRead(
        id="alert-001",
        alert_type="inventory_risk",
        severity="high",
        department_code="PROC",
        title="안전재고 미달 위험 품목 4건",
        message="다음 2주 생산계획 기준 부족 위험",
        source_ref="mart_procurement_risk_daily",
    ),
    AlertRead(
        id="alert-002",
        alert_type="quality_pattern",
        severity="high",
        department_code="QUAL",
        title="반복 불량 패턴 감지",
        message="지난 4주 반복 불량 유형 집중 발생",
        source_ref="fact_quality_inspection",
    ),
]

REPORTS = [
    ReportRead(
        id="report-001",
        title="제조 운영 주간 보고서",
        status="draft_ready",
        report_type="weekly_ops",
        department_code="MES",
        period_start=date(2026, 2, 23),
        period_end=date(2026, 3, 1),
    ),
    ReportRead(
        id="report-002",
        title="품질 이상 패턴 리포트",
        status="approval_pending",
        report_type="quality_risk",
        department_code="QUAL",
        period_start=date(2026, 2, 23),
        period_end=date(2026, 3, 1),
    ),
]

APPROVALS = [
    ApprovalRead(id="approval-001", approval_type="purchase_order", status="pending"),
    ApprovalRead(id="approval-002", approval_type="report_publish", status="pending"),
]

AGENT_RUNS = [
    AgentRunRead(
        id="run-001",
        department_code="PROC",
        route_type="structured_analytics",
        status="completed",
        model_name="router-v0.1",
        policy_version="policy-rbac-v0.1",
    ),
    AgentRunRead(
        id="run-002",
        department_code="QUAL",
        route_type="hybrid_search",
        status="completed",
        model_name="router-v0.1",
        policy_version="policy-rbac-v0.1",
    ),
]

SAVED_QUERIES = [
    SavedQueryRead(
        id="saved-001",
        user_id="user-001",
        title="구매 위험 품목 조회",
        query_text="다음 2주 생산계획 기준으로 안전재고 미달 가능성이 높은 품목과 추천 발주 수량을 보여줘.",
        department_scope="PROC",
        created_at=NOW,
    ),
    SavedQueryRead(
        id="saved-002",
        user_id="user-001",
        title="품질 이상 패턴 분석",
        query_text="지난 4주간 반복 불량 패턴과 원인 후보를 알려줘.",
        department_scope="QUAL",
        created_at=NOW,
    ),
]

AGENT_SOURCES = [
    AgentSourceRead(source_type="sql", source_ref="mart_procurement_risk_daily", relevance_score=0.95),
    AgentSourceRead(source_type="document", source_ref="purchase-policy-v1.2", relevance_score=0.84),
]

DOCUMENTS = [
    DocumentRead(id="doc-001", title="주간 생산 회의록", type="meeting"),
    DocumentRead(id="doc-002", title="품질 클레임 조치 이력", type="claim"),
]

DOCUMENT_SEARCH = DocumentSearchResponse(
    query="반복 불량 패턴",
    results=[
        DocumentSearchResultRead(id="doc-001", title="주간 생산 회의록", score=0.91),
        DocumentSearchResultRead(id="doc-002", title="품질 클레임 조치 이력", score=0.87),
    ],
)

CONNECTOR_RUNS = [
    ConnectorRunRead(
        id="conn-run-001",
        connector_name="ERP",
        started_at=NOW,
        ended_at=NOW,
        status="completed",
        inserted_rows=124,
        updated_rows=32,
    ),
    ConnectorRunRead(
        id="conn-run-002",
        connector_name="MES",
        started_at=NOW,
        ended_at=None,
        status="running",
        inserted_rows=540,
        updated_rows=12,
    ),
]

DEPARTMENT_KPIS = {
    "EXEC": [
        KpiMetricRead(code="budget_execution_rate", label="예산 집행률", value=72.4, unit="%"),
        KpiMetricRead(code="supplier_otd", label="공급사 납기 준수율", value=91.1, unit="%"),
        KpiMetricRead(code="oee", label="OEE", value=83.2, unit="%"),
    ],
    "PROC": [
        KpiMetricRead(code="supplier_otd", label="공급사 납기 준수율", value=91.1, unit="%"),
        KpiMetricRead(code="material_price_delta", label="원자재 단가 변동률", value=4.8, unit="%"),
        KpiMetricRead(code="safety_stock_risk", label="안전재고 미달 품목", value=4, unit="건"),
    ],
    "MES": [
        KpiMetricRead(code="production_target_rate", label="생산 목표 달성률", value=96.2, unit="%"),
        KpiMetricRead(code="equipment_uptime", label="설비 가동률", value=92.4, unit="%"),
        KpiMetricRead(code="oee", label="OEE", value=83.2, unit="%"),
    ],
    "QUAL": [
        KpiMetricRead(code="ppm", label="PPM", value=225, unit="ppm"),
        KpiMetricRead(code="claim_lead_time", label="클레임 처리 리드타임", value=3.2, unit="일"),
        KpiMetricRead(code="defect_ratio", label="불량 유형 비중", value=18.3, unit="%"),
    ],
}

KPI_TREND = [
    KpiTrendPointRead(period="2026-W07", oee=79.4, ppm=310, supplier_otd=88.7),
    KpiTrendPointRead(period="2026-W08", oee=80.8, ppm=284, supplier_otd=89.2),
    KpiTrendPointRead(period="2026-W09", oee=82.5, ppm=240, supplier_otd=90.4),
    KpiTrendPointRead(period="2026-W10", oee=83.2, ppm=225, supplier_otd=91.1),
]

MEETING_DIRECTIVES = [
    MeetingDirectiveRead(
        id="directive-001",
        meeting_date=date(2026, 3, 9),
        department_code="MES",
        category="생산",
        title="자동화 라인 정상화 - HORN 조립부분",
        status="in_progress",
        owner_name="박생산",
        due_date=date(2026, 3, 13),
        source_page=1,
        source_section="생산/생관/제조본부장",
        notes="자동화 라인 가동 안정화와 병목 구간 원인 확인 필요",
    ),
    MeetingDirectiveRead(
        id="directive-002",
        meeting_date=date(2026, 3, 9),
        department_code="QUAL",
        category="품질",
        title="WORST 아이템 집중관리 - INNER SEAL, BUSH 혼입 외",
        status="at_risk",
        owner_name="연규열",
        due_date=date(2026, 3, 12),
        source_page=1,
        source_section="품질",
        notes="반복 불량과 금형 손상 항목을 우선 모니터링하고 개선대책 연결",
    ),
    MeetingDirectiveRead(
        id="directive-003",
        meeting_date=date(2026, 3, 9),
        department_code="PROC",
        category="구매/자재",
        title="구매 수불관리 안정화",
        status="pending",
        owner_name="김구매",
        due_date=date(2026, 3, 14),
        source_page=1,
        source_section="구매·자재/경영지원",
        notes="자재 부족, 미입고, 재고 반영 비율을 재점검하고 주간회의에 보고",
    ),
    MeetingDirectiveRead(
        id="directive-004",
        meeting_date=date(2026, 3, 9),
        department_code="EXEC",
        category="경영지원",
        title="2025년 미결 업무 진행상황 부서별 재점검",
        status="completed",
        owner_name="심현보",
        due_date=date(2026, 3, 11),
        source_page=1,
        source_section="공통 지시사항",
        notes="미결 항목 목록 취합 후 각 부서 실행률 공유 완료",
    ),
]

PRODUCTION_INQUIRIES = [
    ProductionInquiryRead(
        id="prod-inq-001",
        inquiry_no="2025/03/26-1",
        production_date=date(2025, 3, 26),
        workorder_no="P45012",
        status="확인",
        item_code="AX01",
        item_name="스트럿 폼패드 좌품",
        spec="90 x 24",
        unit="EA",
        planned_qty=90,
        receipt_qty=58,
        warehouse="원자재창고",
        remark="신상품재고 재사용",
    ),
    ProductionInquiryRead(
        id="prod-inq-002",
        inquiry_no="2025/03/21-7",
        production_date=date(2025, 3, 21),
        workorder_no="P44987",
        status="진행중",
        item_code="MX5-070",
        item_name="부스가공품",
        spec="70 x 15",
        unit="EA",
        planned_qty=120,
        receipt_qty=64,
        warehouse="반제품창고",
        remark="생산수량 재확인 필요",
    ),
    ProductionInquiryRead(
        id="prod-inq-003",
        inquiry_no="2025/03/17-4",
        production_date=date(2025, 3, 17),
        workorder_no="P44933",
        status="대기",
        item_code=None,
        item_name=None,
        spec=None,
        unit="EA",
        planned_qty=100,
        receipt_qty=0,
        warehouse=None,
        remark="생산품 선택 필요",
    ),
    ProductionInquiryRead(
        id="prod-inq-004",
        inquiry_no="2025/03/06-3",
        production_date=date(2025, 3, 6),
        workorder_no="P44880",
        status="확인",
        item_code="BUSH-760",
        item_name="BUSH 조립품",
        spec="760 TYPE",
        unit="EA",
        planned_qty=80,
        receipt_qty=80,
        warehouse="완제품창고",
        remark="검수 완료",
    ),
]

PRODUCTION_ITEMS = [
    ProductionItemRead(
        id="prod-item-001",
        item_code="AX01",
        item_name="스트럿 폼패드 좌품",
        spec="90 x 24",
        unit="EA",
        available_qty=100,
        process_name="압축성형",
        warehouse="원자재창고",
    ),
    ProductionItemRead(
        id="prod-item-002",
        item_code="MX5-070",
        item_name="부스가공품",
        spec="70 x 15",
        unit="EA",
        available_qty=240,
        process_name="부스가공",
        warehouse="반제품창고",
    ),
    ProductionItemRead(
        id="prod-item-003",
        item_code="HORN-ASM",
        item_name="HORN 조립반제품",
        spec="ASM-SET",
        unit="EA",
        available_qty=68,
        process_name="조립",
        warehouse="생산대기창고",
    ),
    ProductionItemRead(
        id="prod-item-004",
        item_code="BUSH-760",
        item_name="BUSH 조립품",
        spec="760 TYPE",
        unit="EA",
        available_qty=80,
        process_name="검사완료",
        warehouse="완제품창고",
    ),
]

PRODUCTION_PROCESSES = [
    ProductionProcessRead(
        id="proc-flow-001",
        process_no="FLOW-2026-0312-01",
        customer_name="평화산업",
        item_code="HORN-ASM",
        item_name="HORN 조립반제품",
        production_status="in_progress",
        quality_status="pending_inspection",
        inventory_status="shortage",
        plan_qty=120,
        produced_qty=84,
        defect_qty=4,
        available_qty=62,
        ready_qty=58,
        next_action="재고 할당 후 품질검사 진행",
        issue_summary="조립 라인 생산은 진행 중이나 원자재 보충과 품질검사 대기가 동시에 필요합니다.",
    ),
    ProductionProcessRead(
        id="proc-flow-002",
        process_no="FLOW-2026-0312-02",
        customer_name="SECO AIA",
        item_code="BUSH-760",
        item_name="BUSH 조립품",
        production_status="waiting_receipt",
        quality_status="passed",
        inventory_status="allocated",
        plan_qty=80,
        produced_qty=80,
        defect_qty=0,
        available_qty=80,
        ready_qty=80,
        next_action="입고 확정",
        issue_summary="검사 완료 및 재고 할당이 끝나 입고처리만 남아 있습니다.",
    ),
    ProductionProcessRead(
        id="proc-flow-003",
        process_no="FLOW-2026-0312-03",
        customer_name="HKMC",
        item_code="MX5-070",
        item_name="부스가공품",
        production_status="completed",
        quality_status="at_risk",
        inventory_status="allocated",
        plan_qty=240,
        produced_qty=240,
        defect_qty=12,
        available_qty=228,
        ready_qty=216,
        next_action="품질 이슈 검토",
        issue_summary="불량 12ea 발생으로 품질 승인 전 출고 보류 상태입니다.",
    ),
]

INQUIRY_HISTORY: dict[str, list] = {}

PRODUCTION_PROCESS_EVENTS = {
    "proc-flow-001": [
        ProductionProcessEventRead(
            id="event-001",
            process_id="proc-flow-001",
            step_code="production",
            step_label="생산 지시 접수",
            status="completed",
            actor_name="박생산",
            happened_at=NOW,
            detail="작업지시와 일일 생산계획이 확정되어 라인 투입 준비가 완료되었습니다.",
        ),
        ProductionProcessEventRead(
            id="event-002",
            process_id="proc-flow-001",
            step_code="inventory",
            step_label="원자재 부족 알림",
            status="at_risk",
            actor_name="김구매",
            happened_at=NOW,
            detail="조립 부자재 안전재고가 부족해 우선 할당 및 긴급조달이 필요합니다.",
        ),
    ],
    "proc-flow-002": [
        ProductionProcessEventRead(
            id="event-003",
            process_id="proc-flow-002",
            step_code="quality",
            step_label="품질 검사 완료",
            status="completed",
            actor_name="연규열",
            happened_at=NOW,
            detail="LOT 샘플 검사 결과 이상 없음으로 입고 대기 상태로 전환되었습니다.",
        ),
    ],
    "proc-flow-003": [
        ProductionProcessEventRead(
            id="event-004",
            process_id="proc-flow-003",
            step_code="quality",
            step_label="반복 불량 이슈",
            status="at_risk",
            actor_name="연규열",
            happened_at=NOW,
            detail="BUSH 혼입 외 패턴 재발로 품질 승인 보류 및 원인 분석이 필요합니다.",
        ),
    ],
}

PRODUCTION_APPROVALS = {
    "proc-flow-001": [
        ProductionApprovalLogRead(
            id="approval-log-001",
            process_id="proc-flow-001",
            stage="자재 할당",
            approver_name="김구매",
            status="pending",
            comment="부족 수량 보충 후 할당 예정",
        ),
    ],
    "proc-flow-002": [
        ProductionApprovalLogRead(
            id="approval-log-002",
            process_id="proc-flow-002",
            stage="품질 승인",
            approver_name="연규열",
            status="approved",
            decided_at=NOW,
            comment="샘플 검사 및 외관 검사 완료",
        ),
    ],
    "proc-flow-003": [
        ProductionApprovalLogRead(
            id="approval-log-003",
            process_id="proc-flow-003",
            stage="품질 승인",
            approver_name="연규열",
            status="blocked",
            decided_at=NOW,
            comment="반복 불량 12ea 발생으로 승인 보류",
        ),
    ],
}

INVENTORY_SYNC = {
    "proc-flow-001": InventorySyncRead(
        process_id="proc-flow-001",
        warehouse="생산대기창고",
        item_code="HORN-ASM",
        before_qty=62,
        receipt_qty=0,
        after_qty=62,
        sync_status="pending",
        last_synced_at=None,
    ),
    "proc-flow-002": InventorySyncRead(
        process_id="proc-flow-002",
        warehouse="완제품창고",
        item_code="BUSH-760",
        before_qty=80,
        receipt_qty=0,
        after_qty=80,
        sync_status="ready",
        last_synced_at=NOW,
    ),
    "proc-flow-003": InventorySyncRead(
        process_id="proc-flow-003",
        warehouse="반제품창고",
        item_code="MX5-070",
        before_qty=228,
        receipt_qty=0,
        after_qty=228,
        sync_status="blocked",
        last_synced_at=NOW,
    ),
}

# ────────────────────────────── Quality NCR ──────────────────────────────

QUALITY_NCRS: list[QualityNCRRead] = [
    QualityNCRRead(
        id="ncr-001",
        ncr_no="NCR-2026-0312-001",
        detected_at=date(2026, 3, 12),
        department_code="QUAL",
        item_code="HORN-ASM",
        item_name="HORN 조립반제품",
        defect_type="조립 불량",
        defect_qty=4,
        total_qty=84,
        defect_rate=round(4 / 84 * 100, 2),
        status="investigating",
        severity="major",
        detected_by="연규열",
        root_cause="자동화 라인 지그 위치 틀어짐",
        action_taken=None,
        resolved_at=None,
        customer_name="평화산업",
        remark="지그 재조정 후 재검 예정",
    ),
    QualityNCRRead(
        id="ncr-002",
        ncr_no="NCR-2026-0311-002",
        detected_at=date(2026, 3, 11),
        department_code="QUAL",
        item_code="MX5-070",
        item_name="부스가공품",
        defect_type="혼입 불량 (BUSH 혼입)",
        defect_qty=12,
        total_qty=240,
        defect_rate=round(12 / 240 * 100, 2),
        status="open",
        severity="critical",
        detected_by="연규열",
        root_cause=None,
        action_taken=None,
        resolved_at=None,
        customer_name="HKMC",
        remark="반복 불량 패턴 - 원인 분석 긴급 필요",
    ),
    QualityNCRRead(
        id="ncr-003",
        ncr_no="NCR-2026-0305-003",
        detected_at=date(2026, 3, 5),
        department_code="QUAL",
        item_code="BUSH-760",
        item_name="BUSH 조립품",
        defect_type="외관 불량",
        defect_qty=2,
        total_qty=80,
        defect_rate=round(2 / 80 * 100, 2),
        status="resolved",
        severity="minor",
        detected_by="김검사",
        root_cause="도금 공정 온도 편차",
        action_taken="도금 온도 프로파일 수정 및 공정 표준서 갱신",
        resolved_at=date(2026, 3, 8),
        customer_name="SECO AIA",
        remark="재발 방지 대책 완료",
    ),
]

# ────────────────────────────── Inventory Ledger ──────────────────────────────

INVENTORY_LEDGER: list[InventoryLedgerRead] = [
    InventoryLedgerRead(
        id="inv-001",
        item_code="AX01",
        item_name="스트럿 폼패드 좌품",
        spec="90 x 24",
        unit="EA",
        warehouse="원자재창고",
        stock_qty=100,
        safety_stock=50,
        is_below_safety=False,
        last_updated=NOW,
    ),
    InventoryLedgerRead(
        id="inv-002",
        item_code="MX5-070",
        item_name="부스가공품",
        spec="70 x 15",
        unit="EA",
        warehouse="반제품창고",
        stock_qty=38,
        safety_stock=60,
        is_below_safety=True,
        last_updated=NOW,
    ),
    InventoryLedgerRead(
        id="inv-003",
        item_code="HORN-ASM",
        item_name="HORN 조립반제품",
        spec="ASM-SET",
        unit="EA",
        warehouse="생산대기창고",
        stock_qty=62,
        safety_stock=40,
        is_below_safety=False,
        last_updated=NOW,
    ),
    InventoryLedgerRead(
        id="inv-004",
        item_code="BUSH-760",
        item_name="BUSH 조립품",
        spec="760 TYPE",
        unit="EA",
        warehouse="완제품창고",
        stock_qty=18,
        safety_stock=30,
        is_below_safety=True,
        last_updated=NOW,
    ),
    InventoryLedgerRead(
        id="inv-005",
        item_code="SEAL-A",
        item_name="INNER SEAL A",
        spec="TYPE-A",
        unit="EA",
        warehouse="원자재창고",
        stock_qty=5,
        safety_stock=20,
        is_below_safety=True,
        last_updated=NOW,
    ),
]

INVENTORY_TRANSACTIONS: list[InventoryTransactionRead] = [
    InventoryTransactionRead(
        id="tx-001",
        item_code="AX01",
        item_name="스트럿 폼패드 좌품",
        tx_type="receipt",
        qty=58,
        balance_after=100,
        warehouse="원자재창고",
        reference_no="2025/03/26-1",
        actor_name="창고담당",
        tx_at=NOW,
        note="생산입고 확정",
    ),
    InventoryTransactionRead(
        id="tx-002",
        item_code="MX5-070",
        item_name="부스가공품",
        tx_type="issue",
        qty=60,
        balance_after=38,
        warehouse="반제품창고",
        reference_no="WO-HKMC-0312",
        actor_name="생산담당",
        tx_at=NOW,
        note="생산투입 출고",
    ),
    InventoryTransactionRead(
        id="tx-003",
        item_code="BUSH-760",
        item_name="BUSH 조립품",
        tx_type="receipt",
        qty=80,
        balance_after=80,
        warehouse="완제품창고",
        reference_no="2025/03/06-3",
        actor_name="창고담당",
        tx_at=NOW,
        note="검수 완료 후 입고",
    ),
    InventoryTransactionRead(
        id="tx-004",
        item_code="BUSH-760",
        item_name="BUSH 조립품",
        tx_type="issue",
        qty=62,
        balance_after=18,
        warehouse="완제품창고",
        reference_no="SO-SECO-0311",
        actor_name="출하담당",
        tx_at=NOW,
        note="고객 출하",
    ),
    InventoryTransactionRead(
        id="tx-005",
        item_code="SEAL-A",
        item_name="INNER SEAL A",
        tx_type="adjust",
        qty=-15,
        balance_after=5,
        warehouse="원자재창고",
        reference_no="ADJ-2026-03",
        actor_name="재고담당",
        tx_at=NOW,
        note="실사 조정 (불량 파손 폐기)",
    ),
]
